export class InvalidTableNameError extends Error {
  constructor(tableName: string) {
    super(
      `Invalid table name "${tableName}". Must be snake_case (lowercase letters, digits, underscores) and start with a letter.`,
    );
    this.name = 'InvalidTableNameError';
  }
}

function validateTableName(tableName: string): void {
  if (!tableName || !/^[a-z][a-z0-9_]*$/.test(tableName)) {
    throw new InvalidTableNameError(tableName);
  }
}

export function generateRlsMigrationSql(tableName: string): string {
  validateTableName(tableName);

  return `-- Enable Row-Level Security for table: ${tableName}
-- Generated by: pnpm --filter @taller-saas/api ts-node scripts/generate-rls-migration.ts ${tableName}
-- Reference: docs/adr/0001-multi-tenancy-strategy.md

ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${tableName} FORCE ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON ${tableName}
  USING (tenant_id = current_setting('app.tenant_id', true)::uuid)
  WITH CHECK (tenant_id = current_setting('app.tenant_id', true)::uuid);

GRANT SELECT, INSERT, UPDATE, DELETE ON ${tableName} TO taller_app;
`;
}
